package com.zk.gymos.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.util.UUID;

/**
 * App profile row in {@code public.users}. The primary key equals the Supabase Auth user id
 * ({@code auth.users.id}); credentials (email/phone/password) live in Supabase, not here.
 * Rows are normally created by a Supabase trigger on sign-up, so the backend only reads them.
 */
@Getter
@Setter
@Entity
@Table(name = "users")
public class User extends BaseEntity {

    /** Same uuid as the Supabase Auth account; not generated by this app. */
    @Id
    private UUID id;

    @Column(nullable = false, length = 50)
    private String nickname;

    @Column(length = 100)
    private String email;

    /** Avatar URL (text). */
    @Column(columnDefinition = "text")
    private String avatar;
}
